export interface Quote {
  text: string;
  source: string;
  year: number;
}

export const quotes: Quote[] = [
  { text: "Quand on me provoque, je ne réponds pas. J'agis.", source: "Walker, Texas Ranger", year: 1993 },
  { text: "La justice ne dort jamais.", source: "Walker, Texas Ranger", year: 1995 },
  { text: "Je n'ai pas besoin d'armes. Je suis une arme.", source: "Missing in Action", year: 1984 },
  { text: "On ne choisit pas le moment du combat. Mais on choisit de se battre.", source: "Delta Force", year: 1986 },
  { text: "Si tu veux la paix, prépare-toi à la guerre.", source: "Invasion U.S.A.", year: 1985 },
  { text: "Le courage, c'est d'avoir peur mais d'agir quand même.", source: "Lone Wolf McQuade", year: 1983 },
  { text: "La loi, c'est moi.", source: "Walker, Texas Ranger", year: 1998 },
  { text: "Je reviens toujours. Toujours.", source: "The Expendables 2", year: 2012 },
  { text: "Un homme sans honneur n'est rien.", source: "Code of Silence", year: 1985 },
  { text: "Le mal ne triomphe que lorsque les hommes de bien ne font rien.", source: "Walker, Texas Ranger", year: 2001 },
  { text: "Ma patience a des limites. Et tu viens de les atteindre.", source: "Missing in Action 2", year: 1985 },
  { text: "Dans la vie, tu es soit le chasseur, soit la proie.", source: "Lone Wolf McQuade", year: 1983 },
  { text: "On ne négocie pas avec le mal. On l'élimine.", source: "Delta Force", year: 1986 },
  { text: "Chaque cicatrice raconte une histoire. La mienne raconte la victoire.", source: "Walker, Texas Ranger", year: 1996 },
  { text: "La force sans la sagesse n'est que destruction.", source: "Walker, Texas Ranger", year: 1997 },
  { text: "Tu crois que tu peux me faire peur ? Tu ne sais même pas ce qu'est la peur.", source: "Silent Rage", year: 1982 },
  { text: "Je ne me bats pas pour la gloire. Je me bats parce que c'est juste.", source: "Forced Vengeance", year: 1982 },
  { text: "Le monde est plein de gens qui parlent. Moi, j'agis.", source: "An Eye for an Eye", year: 1981 },
  { text: "Quand je donne ma parole, c'est un contrat avec Dieu.", source: "Walker, Texas Ranger", year: 1994 },
  { text: "La vengeance est un plat qui se sert avec un roundhouse kick.", source: "A Force of One", year: 1979 },
  { text: "Les bons portent du noir aussi.", source: "Good Guys Wear Black", year: 1978 },
  { text: "Personne ne touche à ma famille. Personne.", source: "Braddock: Missing in Action III", year: 1988 },
  { text: "La différence entre toi et moi ? Moi, je suis toujours debout.", source: "The Hitman", year: 1991 },
  { text: "Tu peux courir, mais tu ne feras que mourir fatigué.", source: "Hero and the Terror", year: 1988 },
  { text: "Un vrai guerrier ne cherche pas le combat. Le combat le trouve.", source: "The Octagon", year: 1980 },
  { text: "La route est longue, mais mes poings sont patients.", source: "Breaker! Breaker!", year: 1977 },
  { text: "Si tu veux danser, je choisis la musique.", source: "Firewalker", year: 1986 },
  { text: "Les rêves ne fonctionnent que si tu te lèves et que tu te bats.", source: "Sidekicks", year: 1992 },
  { text: "On m'a dit que c'était impossible. Ça m'a motivé.", source: "Walker, Texas Ranger", year: 1999 },
  { text: "Le silence est ma meilleure réponse. Mon poing est la deuxième.", source: "Missing in Action", year: 1984 },
  { text: "Là où il y a de l'injustice, il y aura toujours quelqu'un pour se lever.", source: "Walker, Texas Ranger", year: 2000 },
  { text: "Un homme se mesure à la façon dont il traite ceux qui ne peuvent pas se défendre.", source: "Walker, Texas Ranger", year: 1996 },
  { text: "La loyauté n'est pas un mot. C'est un mode de vie.", source: "Delta Force", year: 1986 },
  { text: "Quand le monde s'effondre, je reste debout.", source: "Invasion U.S.A.", year: 1985 },
  { text: "Je ne cherche pas les ennuis. Les ennuis me cherchent.", source: "Top Dog", year: 1995 },
  { text: "La vraie force, c'est de savoir quand ne pas frapper.", source: "Walker, Texas Ranger", year: 1997 },
  { text: "Ils pensaient m'avoir brisé. Ils m'ont rendu plus fort.", source: "Missing in Action 2", year: 1985 },
  { text: "Certains hommes naissent pour protéger. Je suis l'un d'entre eux.", source: "Lone Wolf McQuade", year: 1983 },
  { text: "Tu ne peux pas acheter l'honneur. Tu le gagnes avec du sang.", source: "Forced Vengeance", year: 1982 },
  { text: "Le Texas n'est pas assez grand pour nous deux.", source: "Walker, Texas Ranger", year: 1993 },
  { text: "La nuit appartient aux braves.", source: "Code of Silence", year: 1985 },
  { text: "Mes méthodes sont peu orthodoxes. Mais elles fonctionnent.", source: "Walker, Texas Ranger", year: 1995 },
  { text: "Quand la diplomatie échoue, il reste mes poings.", source: "Delta Force", year: 1986 },
  { text: "Le passé est derrière moi. Le futur tremble devant moi.", source: "The Expendables 2", year: 2012 },
  { text: "Un seul homme peut changer le monde. Je suis cet homme.", source: "Invasion U.S.A.", year: 1985 },
  { text: "La douleur est temporaire. La légende est éternelle.", source: "Sidekicks", year: 1992 },
  { text: "Je ne fais pas de promesses. Je fais des garanties.", source: "Walker, Texas Ranger", year: 1998 },
  { text: "Derrière chaque grand homme, il y a son roundhouse kick.", source: "A Force of One", year: 1979 },
  { text: "Tu as choisi le mauvais jour pour être du mauvais côté.", source: "Braddock: Missing in Action III", year: 1988 },
  { text: "Les héros ne meurent jamais. Ils s'en vont simplement.", source: "The Expendables 2", year: 2012 },
];
